    - name: Fix shebang bug in RCU
      ansible.builtin.lineinfile:
        path: '{{ base_path }}/oracle/middleware/oracle_common/bin/rcu'
        regexp: /bin/sh
        line: "#!/bin/bash"
    - name: Copy Configuration Assistant response file
      ansible.builtin.copy:
        src: response-files/config-assistant.rsp
        dest: '{{ base_path }}'
        mode: "0600"
    - name: Delete Linux distribution pre-req check
      ansible.builtin.file:
        path: '{{ base_path }}/oracle/middleware/oui/mw/bi/prereq/linux64/LinuxVendors.xml'
        state: absent
    - name: Run Configuration Assistant
      ansible.builtin.command: '{{ base_path }}/oracle/middleware/bi/bin/config.sh -silent -responseFile {{ base_path }}/config-assistant.rsp -ignoreSysPreReqs'
      args:
        creates: '{{ base_path }}/oracle/middleware/user_projects/domains/bi/config/fmwconfig/servers/AdminServer/dms_config.xml'
      environment:
        JAVA_HOME: /opt/jdk/jdk1.8.0_202
