---
- name: Deploy Oracle Analytics Server
  hosts: instances
  vars:
    base_path: /home/ubuntu
  remote_user: root
  tasks:
    - name: Create swapfile
      ansible.builtin.import_role:
        name: create-swapfile
      when: ansible_swaptotal_mb < 1

    - name: Install unzip
      ansible.builtin.apt:
        pkg: unzip
      become: true
      become_user: root

    - name: Check JDK
      ansible.builtin.stat:
        path: '/opt/jdk/jdk1.8.0_202/LICENSE'
      register: jdk_file
    - name: Install JDK
      ansible.builtin.import_role:
        name: jdk
      when: not jdk_file.stat.exists

    - name: Check Middleware
      ansible.builtin.stat:
        path: '{{ base_path }}/oracle/middleware/oraInst.loc'
      register: middleware_file
    - name: Install Middleware
      ansible.builtin.import_role:
        name: middleware
      when: not middleware_file.stat.exists

    - name: Check OAS
      ansible.builtin.stat:
        path: '{{ base_path }}/oracle/middleware/inventory/Components/oracle.bi.dataload.oas/2.0.7.0.0/compDef.xml'
      register: oas_file
    - name: Install OAS
      ansible.builtin.import_role:
        name: oas-install
      when: not oas_file.stat.exists

    - name: Check SQL Server
      ansible.builtin.stat:
        path: "{{ base_path }}/.mssql-configured"
      register: sql_file
    - name: Install SQL Server
      ansible.builtin.import_role:
        name: sql-server
      when: not sql_file.stat.exists

    - name: Check OAS Configuration
      ansible.builtin.stat:
        path: '{{ base_path }}/oracle/middleware/user_projects/domains/bi/config/fmwconfig/servers/AdminServer/dms_config.xml'
      register: oas_config_file
    - name: Apply OAS Configuration
      ansible.builtin.import_role:
        name: oas-configuration
      when: not oas_config_file.stat.exists
